[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 2

remappings = ["@solady/=lib/solady/"]


[profile.verbose]
verbosity = 4

[fuzz]
runs = 5000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
